### ISSUE TITLE
The icon isn't displayed correctly in the title bar

### ISSUE THREAD

**Issue by DonKadaj** [benruehl/adonis-ui#111] opened 2020-07-19 09:35 UTC
**Describe the bug**
I use an ico file (which embed several icon sizes) for my application logo. Usually, Windows chooses the best size to display. However, with `AdonisUI.Controls.AdonisWindow` the size isn't adjusted in the title bar.

**Screenshots**
The icon displayed from `Windows`:
![image](https://user-images.githubusercontent.com/54101733/87871397-3c38bd80-c9b0-11ea-98e6-bf4a6e771aac.png)
The icon displayed from `AdonisUI.Controls.AdonisWindow` (it uses an oversized icon):
![image](https://user-images.githubusercontent.com/54101733/87871452-afdaca80-c9b0-11ea-92cb-166379946fc7.png)

**Comment by benruehl** [comment] 2020-08-23 17:47
Thank you for reporting this issue. And sorry for the late reply.

I tried to reproduce this with different .ico files but couldn't achieve the effect you had. For me, all icons I tried look the same in both window classes.

Would you mind uploading your file here so I can use it for reproduction?

**Comment by DonKadaj** [comment] 2020-08-29 07:51
I sent you an email with my icon. I hope this will be useful to you.

**Comment by irusanov** [comment] 2020-09-07 21:10
@benruehl I have the same problem.
16x16 icon is picked for titlebar when main windows does not inherit AdonisWindow.
The icon I have includes common sizes and works correctly in Windows Forms and WPF without Adonis UI.
It's not horrible, but the largest size is picked for the titlebar, instead of the 16x16 version.

ICO file attached: [ZenTimings.ico.zip](https://github.com/benruehl/adonis-ui/files/5184907/ZenTimings.ico.zip)

Current result
![image](https://user-images.githubusercontent.com/7671877/92416657-3452f980-f167-11ea-81e5-394d609d01a8.png)

Expected:
![image](https://user-images.githubusercontent.com/7671877/92416763-bcd19a00-f167-11ea-8c0c-9248f19a6ebd.png)

**Comment by benruehl** [comment] 2020-09-13 14:52
Ok guys, good and bad news.

**Good news:**
I can reproduce the issue with your files. Thanks to both of you @DonKadaj @irusanov.

**Bad news:**
I don't know how to fix it :(

At the moment, I use `System.Drawing.Icon.ExtractAssociatedIcon(absolutePathToExecutable)` to get the icon that has been specified for the application. Unfortunately, this retrieves the 32x32 version only [[Source](https://stackoverflow.com/a/4981959) in comments]. There is no overload or anything to specify a size.

I found a different approach [here](https://stackoverflow.com/a/7024970) which looked promising but unfortunately this throws a `COMException` for me. I couldn't get it to run. My guess is that this might only work with an URI in pack syntax like `"pack://application:,,,"`. Using this syntax is not an option though because Adonis UI does not know the name and location of the icon file. And I don't like the idea that the developer has to specify an icon path for each window.

Last thing I found was some ugly interop magic [here](https://stackoverflow.com/a/29819585). This is a lot of code for such a simple requirement but I tested it anyway. It didn't work though. I cannot say why because there is no exception raised or anything. The rednered icon simply becomes a generic placeholder icon.

**Possible workaround:**
Even though I don't know how to fix it for the library you might be able to fix it for your cases individually.
Where you have your window class (probably `MainWindow`) deriving from `AdonisWindow` you could go to your code-behind file and look for the constructor. `AdonisWindow` displays its icon via the `IconSource` property which you can set on your own. The following code solved the issue for me. Make sure the **build action** of the icon file is set to **Content**.

```csharp
public MainWindow()
{
    InitializeComponent();

    // Try to get your icon in the correct size here and assign it.
    IconSource = GetIcon("pack://application:,,,/AdonisUI.Demo;component/ZenTimings.ico", 16);
}

private ImageSource GetIcon(string iconSource, double width)
{
    var decoder = BitmapDecoder.Create(new Uri(iconSource),
        BitmapCreateOptions.DelayCreation,
        BitmapCacheOption.OnDemand);

    var result = decoder.Frames.SingleOrDefault(f => f.Width == width);
    if (result == default(BitmapFrame))
    {
        result = decoder.Frames.OrderBy(f => f.Width).First();
    }

    return result;
}
```

You can try different methods of loading an icon if you want. I linked some resources that might help.
Hope this helps.

**Comment by irusanov** [comment] 2020-09-14 11:57
Yes, that approach works for me. Thanks!
I've tried some of the linked solutions before, but they didn't work for me either.
Was not really keen on that interop core for just a simple icon, so I left it as it is, but will use that last solution you proposed.

**Comment by benruehl** [comment] 2020-09-14 21:39
Good to hear that this works for you :)

I will close this issue then although the solution does not feel really satisfying to me.

**Closed by benruehl** 2020-09-14 21:39 UTC
Labels: bug

**Comment by DonKadaj** [comment] 2020-09-15 18:07
Thanks @benruehl for all your research!

I found another workaround (if we can call it that), instead of setting the icon in the XAML file, just set it in the app properties: **Project > Properties > Application tab**.

![image](https://user-images.githubusercontent.com/54101733/93246958-d4270d80-f78d-11ea-8189-36debd37f021.png)

**Comment by irusanov** [comment] 2020-09-15 18:10
@DonKadaj This is my usual way of setting the application icon, but it did not work - it didn't matter if it is defined in the project properties or in the XAML file.

**Comment by DonKadaj** [comment] 2020-09-16 18:19
@irusanov Make sure to remove the `Icon="YourIconPath"` in your XAML file, because it seems to override the icon set in the project properties. This is the case for me.

**Comment by irusanov** [comment] 2020-09-16 18:47
@DonKadaj That's how I have it from the beginning and the higher resolution of the icon is loaded.
