### ISSUE TITLE
Binding errors when using ComboBox

### ISSUE THREAD

**Issue by nkristek** [benruehl/adonis-ui#18] opened 2019-04-05 20:36 UTC
I noticed, that the application output is filled with messages, that a BindingExpression path error occured, when using a ComboBox:
```
System.Windows.Data Error: 40 : BindingExpression path error: '(adonisExtensions:WatermarkExtension.IsWatermarkVisible)' property not found on 'object' ''ComboBox' (Name='')'. BindingExpression:Path=(adonisExtensions:WatermarkExtension.IsWatermarkVisible); DataItem='ComboBox' (Name=''); target element is 'TextBox' (Name='PART_EditableTextBox'); target property is 'NoTarget' (type 'Object')
Exception thrown: 'MS.Internal.Xaml.Parser.GenericTypeNameParser.TypeNameParserException' in System.Xaml.dll
System.Windows.Data Error: 40 : BindingExpression path error: '(adonisExtensions:WatermarkExtension.Watermark)' property not found on 'object' ''ComboBox' (Name='')'. BindingExpression:Path=(adonisExtensions:WatermarkExtension.Watermark); DataItem='ComboBox' (Name=''); target element is 'ContentPresenter' (Name='PlaceholderHost'); target property is 'Content' (type 'Object')
Exception thrown: 'MS.Internal.Xaml.Parser.GenericTypeNameParser.TypeNameParserException' in System.Xaml.dll
```
These two errors occur for every ComboBox in my view.
I'm using the latest version of AdonisUI (1.9), I haven't noticed this with earlier versions but I have not tested it specifically with other versions of AdonisUI.
[This](https://github.com/nkristek/Stein/blob/f51884b5295645422214d2ea853711694bbc54b7/src/Stein.Views/ApplicationView.xaml) is the view, the error occurs, the following code snippet is the ComboBox in the view:
```xaml
<ComboBox Grid.Column="0"
          ItemsSource="{Binding InstallerBundles}"
          SelectedItem="{Binding SelectedInstallerBundle}"
          HorizontalContentAlignment="Stretch"
          ScrollViewer.CanContentScroll="True"
          VirtualizingStackPanel.IsVirtualizing="True"
          VirtualizingStackPanel.VirtualizationMode="Recycling"
          VirtualizingStackPanel.ScrollUnit="Pixel">

    <ComboBox.ItemsPanel>
        <ItemsPanelTemplate >
            <VirtualizingStackPanel/>
        </ItemsPanelTemplate>
    </ComboBox.ItemsPanel>
</ComboBox>
```

The view for an installer bundle consists of only a single TextBox:
```xaml
<TextBlock TextTrimming="CharacterEllipsis"
           Text="{Binding Name}"/>
```

There seems to be no error while using the application, I just wanted to check, if the errors can be ignored.

**Comment by benruehl** [comment] 2019-04-07 15:12
I cannot reproduce this behavior with ComboBoxes but I get similar output for TabControls.

I found [this blog post](https://weblogs.asp.net/akjoshi/resolving-un-harmful-binding-errors-in-wpf) stating that they are harmless and handled internally. It seems the error can occur for all controls that contain dynamically created lists.

To resolve the binding errors you could try to explicitly set the watermark to `{x:Null}` or an empty string. As I cannot reproduce it, I cannot test that for you.
Alternatively you can change the log level globally as shown [here](https://www.codeproject.com/Tips/124556/How-to-suppress-the-System-Windows-Data-Error-warn).

**Comment by benruehl** [comment] 2019-04-07 15:22
Oh wait I just noticed that you received BindingError 40 and I get BindingError 4. My answer was supposed to target BindingError 4. I will do some research again but as I cannot reproduce it, it will be hard to tackle.

**Comment by benruehl** [comment] 2019-04-14 14:06
I created a small application where I tried to recreate your setup and finally got the errors as well.

Writing
```xml
<DataTrigger Binding="{Binding Path=(adonisExtensions:WatermarkExtension.IsWatermarkVisible)}"/>
```
instead of
```xml
<DataTrigger Binding="{Binding (adonisExtensions:WatermarkExtension.IsWatermarkVisible)}"/>
```
fixed it for me.

Please reopen in case the errors are still present in your application.

**Closed by benruehl** 2019-04-14 14:06 UTC
Labels: question
