### ISSUE TITLE
Memory leak ?

### ISSUE THREAD

**Issue by maximilien-noal** [benruehl/adonis-ui#109] opened 2020-07-04 21:20 UTC
**Describe the bug**

A memory leak seems to live in adonisUI (tested with v1.16.0 but it seems to be older than that).

**To Reproduce**
1. Clone and startup [RoleDDNG](https://github.com/maximilien-noal/RoleDDNG)
2. Make the Memory Usage tab from the Diagnostic Tools window visible
3. Fire up the Dice Roller 'Window' (or "Lanceur de dés") with the **keybinding** (this is important) Ctrl-D and hold it. 
4. See the memory usage grow and grow over time. Moving the mouse along  at the same time seems to make it grow faster.

**Expected behavior**

Same as the "memleak" branch on the same repo (where adonisUI was removed) : no memory leak.

**Screenshots**

master branch :
![memleak](https://user-images.githubusercontent.com/1087524/86521087-72246080-be4c-11ea-86ed-07b4e1abf970.png)

This goes on forever and grows up to hundred of megabytes, even gigabytes, pretty quickly.

memleak branch :
![nomemleak](https://user-images.githubusercontent.com/1087524/86521115-e6f79a80-be4c-11ea-892b-0856bb4b0d5d.png)

This quickly stabilizes around 175 MB.

**Additional context**

Granted, constantly firing a keybinding isn't an expected "real user" behavior, but still.
No mem leak seems to happen if you close the 'window' first (by clicking on the 'x' button).
Key code points :
- MainViewModel#AddMdiWindow
- MDIContainer#OnSelectionChanged

**Comment by benruehl** [comment] 2020-07-18 12:23
Thank you for your report and sorry for the late reply! I am really busy lately.

I cloned your repo but cannot run it unfortunately. It fails at resolving some `Hammer.MDIContainer.Control` dependency.
Are there any setup instructions?

**Comment by maximilien-noal** [comment] 2020-07-18 12:58
It's inside the Controls directory and should be a local reference. It's a fork of the nuget package of the same name. I think you could use the nuget version instead and still reproduce the issue.
If it fails, I'll try to setup a minimal reproduction repo.

**Comment by benruehl** [comment] 2020-07-18 16:05
I can't get it to run, sorry.

Switching to the NuGet version gives me an error that it does not support build target `netcoreapp3.1`.

Seems like `Hammer.MDIContainer.Control` itself is fine but it has a reference to `Xceed.Wpf.Toolkit` which cannot be resolved again. I noticed that this is placed as a local copy in your repo as well but does not get downloaded when cloning the repo. So I downloaded it manually and placed it in the empty directory `wpftoolkit`. Now the solution loads correctly but Visual Studio does not build anymore. It does not even start a build. It just pops up a message box that sais something like "Error: Interface is not supported".

The log file states: "Visual Studio ran into an unexpected problem with 'Axeed.Wpf.Toolkit'. System.ArgumentException: The project configuration "Debug|AnyCPU" was not found in the project manifest."

**Comment by maximilien-noal** [comment] 2020-07-18 16:16
Sorry about this mess.

I removed wpftoolkit from all branches. It wasn't used anyway. it should work now.

**Comment by benruehl** [comment] 2020-07-18 16:48
It runs now and I can reproduce the increasing memory consumption. I will try to find the source of this.

**Comment by Mgamerz** [comment] 2020-07-21 15:26
Is this related to memory leak I reported here: https://github.com/benruehl/adonis-ui/issues/43 ?

**Comment by maximilien-noal** [comment] 2020-07-29 10:36
@benruehl : Thank you for looking into it.

My bet was on events, but I didn't have time either to look into it.

**Comment by maximilien-noal** [comment] 2020-08-18 12:08
Is there anything we can do to help ?

**Comment by benruehl** [comment] 2020-08-23 22:23
Small update:

Last time I tried some VS memory profiling but didn't find anything unexprected. I am not used to debugging memory leaks so I might have made mistakes here.

Now I did a fresh restart. I cloned your repo again and noticed that the leak does not occur anymore. Looks like you fixed it by not instantiating new windows when holding down the keyboard shortcut. Anyway, I removed the check for existing windows and got the memory leak again. Then I disabled the ripple effect because @Mgamerz suggested it might be the reason. But nothing changed. I disabled the cursor spotlight as well but nothing changed still. I excluded all default styles and then excluded Adonis UI completely but nothing changed. And by "excluded Adonis UI" I mean I removed every single usage in all projects and the project references so that no DLL of Adonis UI can be found in the output directory.

I am a little confused now. To me it looks like this does not have anything to do with Adonis UI. Maybe it's an issue of the MDIContainers you used. Am I missing something here? Please tell me if I did a mistake and came to the wrong conclusion.

**Comment by Mgamerz** [comment] 2020-08-23 22:47
Since you have an open source project, you should be able to get a free
resharper license from jetbrains, if you're interested. I use their
dotmemory program which I find much easier than visual studio's memory
tools.

I trace memory leaks by attaching a weak reference in the constructor of my
windows and objects and then monitor for when they go dead. Once I find
something is not being released that should be, I use dotmemory to find the
root path which is almost always some event handler not being unset.

I'm not sure the issue is the same for my app as the one here but that's
how I traced it to Adonis. I used an older version when I reported my
issue, it could be it was unintentionally fixed since. In my implementation
I use weak event handlers which don't count as a reference for an object,
but at a cost to performance. How much, I don't know. Whenever I get back
to working on my app I might be able to take a look when I pull the latest
code.

**Comment by benruehl** [comment] 2021-01-10 21:30
Closing this because it seems like the issue is not caused by Adonis UI and the ticket didn't receive any attention for quite some time now.

**Closed by benruehl** 2021-01-10 21:30 UTC
Labels: bug
